# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title  A random walk Metropolis sampler using Rcpp
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @param sigma the variance
#' @param x0 the initial value
#' @param N  the length of the chain
#' @return x  a chain 
#' @examples
#' \dontrun{
#' rw -> rwMetropolis(2,25,2000)
#' }
#' @export
rwMetropolis <- function(sigma, x0, N) {
    .Call('_StatComp20067_rwMetropolis', PACKAGE = 'StatComp20067', sigma, x0, N)
}

